package com.lul.dto;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.math.BigDecimal;

/**
 * Data Transfer Object for dashboard summary information
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
public class DashboardSummaryDto {
    /**
     * Total number of transactions in the system
     */
    private long totalTransactions;
    
    /**
     * Total monetary value of all transactions
     */
    private BigDecimal totalTransactionValue;
    
    /**
     * Count of users who have been active recently
     */
    private long activeUsers;
    
    /**
     * Total revenue generated by the platform (from transaction fees)
     */
    private BigDecimal totalRevenue;
} 